version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/mongo
hooks:
  AfterInstall:
   - location: setup.sh
     timeout: 300
  
  ApplicationStart:
   - location: run.sh
     timeout: 300
