name: Docker Image CI
env:
  AWS_REGION_KEY: "eu-north-1"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

#   continuous-integration:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag vladqq/ci
#     - name: Push the Dokcer image  
#       run: docker login -u vladqq -p ${{ secrets.DOCKER_TOKEN }} && docker push vladqq/ci
  
  continuous-deployment:
    runs-on: ubuntu-latest
#    needs: [continuous-integration]
    steps:
     # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION_KEY }}

     # Step 2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name Git_Apllication \
            --deployment-group-name dev \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}    
       
