name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vladqq/CI
    - name: Push the Dokcer image  
      run: docker login -u vladqq -p ${{ secrets.DOCKER_TOKEN }} && docker push vladqq/CI
